name: Simple go Build       # The workflow is assigned a name.


on: # The on event identifier.
  push:
    branches:
      - main                # This workflow is triggered when a push operation
                            # is done to the branch main in this GitHub 
                            # repository

jobs: # Starts the job portion of the workflow
  build: # There is one job in this workflow, named build.
    runs-on: ubuntu-latest  # This job will be executed on a runner system, 
                            # hosted by GitHub provisioned with a standard 
                            # ubuntu operating system image.    
    
    steps: # This starts the series of steps for this job.
    - uses: actions/checkout@v3 # The first step is done via pulling in a
                                # in a predefined action. Note the way it is 
                                # referenced. actions/checkout@v3 refers to the
                                # relative path after github.com, so this really 
                                # says it is going to run/use the action defined
                                # at github.com/actions/checkout.

    - name: Setup Go version    # The hyphen at the start of the line indicates
                                # this is the start of a second step. This line 
                                # is giving the step a new name.
      uses: actions/setup-go@v2 # This same step is pulling in another predefined
                                # action to setup the Go envirnonment.
      with: # The setup-go action needs a parameter -- the version of Go to use.
            # The parameter is passed as an input to the action via a 
            # 'with' clause.   
        go-version: '1.15.1'
    - run: go run hello-world.go    # This is another step, one that simply runs
                                    # a command indicated by the run keyword. 
                                    # The command is to execute the go run
                                    # run command on an example file in the repo.



    